version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
    depends_on:
      - db

  db:
    image: chroma_db_image  # Replace with the actual Docker image for Chroma DB
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"  # Adjust ports as needed for your setup
